# Generated by Django 5.0 on 2024-10-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_task"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="category",),
    ]
